from pydantic import BaseModel, Field
from typing import Optional, List, Dict

from prometheus.data_models.action import ActionOutput, ActionRequest

class ExecutorContext(BaseModel):
    """
    Executor Context is practically the same class as Plan (generated by Planner agent)
    But it contains action_output.
    ExecutorAgent returns object of this class.
    """
    class ExecutionSteps(BaseModel):
        class ControlData(BaseModel):
            id: Optional[str] = None
            depends_on: Optional[List[str]] = None
            ref_output_as: Optional[str] = None

        message: Optional[str] = None
        intent: Optional[str] = None

        action_request: Optional[ActionRequest] = None
        action_output: Optional[ActionOutput] = None

        control: Optional[ControlData] = None

    executed: Optional[Dict[str, ExecutionSteps]] = Field(default_factory=dict)

    def add_step(self, execution_step: ExecutionSteps):
        key = execution_step.control.ref_output_as

        if key is None:
            raise ValueError("ExecutionStep.control.ref_output_as is None; cannot store in executed dict.")

        self.executed[key] = execution_step

    def __getitem__(self, item: str):
        return self.executed[item]

    def __iter__(self):
        return iter(self.executed)
