from pydantic import BaseModel, Field, model_validator
from typing import TypeAlias, Union, Literal
import json

from dotenv import load_dotenv
import os

import logging

logger = logging.getLogger("prometheus.config")

Config: TypeAlias = dict[str, str]

class ModelConfig(BaseModel):
    """
    ModelConfig is a class which contains all needed fields for the model to work.
    name -> which llm to use
    base_url -> base url of the API to use
    max_tokens -> maximum number of tokens the model can generate
    temperature -> "creativity" of the model
    """
    name: str
    base_url: str
    api_key: str
    max_tokens: int = Field(default = 4096, le = 8192, description = "max_tokens max value is 8192.")
    temperature: float = Field(default = 0.2, ge = 0.0, le = 1.0, description = "temperature value should be between 0 - 1.")

    def get_public(self):
        """
        Returns model_config but without base_url and api_key.
        :return:
        """
        return self.model_dump(exclude = {"base_url", "api_key"})

class AgentConfig(BaseModel):
    """
    AgentConfig is a class which contains all needed information for the model.
    prompt -> the agents prompt
    model_config_ can be "inherit", new model_config object or a dict with overwritten settings.
    """
    prompt: str
    model_config_: Union[Literal["inherit"], ModelConfig, dict] = "inherit"

    prompt_content: str = ""
    response_format: dict[str, dict] | None = None

    @model_validator(mode = "after")
    def load_prompt(self):
        """ Automatically load prompt after initialization """
        try:
            with open(self.prompt, "r") as f:
                self.prompt_content = f.read()

        except FileNotFoundError:
            logger.error(f"Prompt file not found: {self.prompt}")
            self.prompt_content = ""

        return self

    def load_response_format(self, response_format):
        """ Load response format generated by AgentPrompt. """
        self.response_format = response_format

    def get_public(self):
        return {
            "model_config": self.model_config_.get_public()
        }

    def get_full_public(self):
        """
        Get whole agent config but with public version of model_config
        """
        return {
            "prompt": self.prompt,
            "model_config": self.model_config_.get_public(),
            "prompt_content": self.prompt_content,
            "response_format": self.response_format
        }

class ActionManagerConfig(BaseModel):
    think_agent: AgentConfig
    code_agent: AgentConfig

    def get_public(self):
        """ Cleans the AgentConfig of action agents so the API can fetch it. """
        public_data = {}

        for field_name, field_value in self.__dict__.items():
            if hasattr(field_value, "get_public"):
                public_data[field_name] = field_value.get_public()

            else:
                public_data[field_name] = field_value

        return public_data

class PrometheusConfig(BaseModel):
    """
    Config for Prometheus (main agent)
    """
    global_model_config: ModelConfig | None = None

    main_agent: AgentConfig

    workflow: AgentConfig
    reflector: AgentConfig

    action_manager: ActionManagerConfig

    def get_public(self):
        """ Same things as action manager config. """
        public_data = {}

        for field_name, field_value in self.__dict__.items():
            if isinstance(field_value, AgentConfig):
                public_data[field_name] = field_value.get_public()

            elif hasattr(field_value, "get_public"):
                public_data[field_name] = field_value.get_public()

            else:
                public_data[field_name] = field_value

        return public_data

    def _resolve_model_config(self, agent_config: AgentConfig, global_model_config: ModelConfig):
        """
        Determines the value of model config based on what is supplied in the config file.
        :param agent_config:
        :param global_model_config:
        :return:
        """
        # inherit config
        if agent_config.model_config_ == "inherit":
            return global_model_config.model_copy()

        # new separate config
        elif isinstance(agent_config.model_config_, ModelConfig):
            return agent_config.model_config_

        # merge configs
        elif isinstance(agent_config.model_config_, dict):
            merged = global_model_config.model_dump()
            merged.update(agent_config.model_config_)

            return ModelConfig(**merged)

    def init_model_cfg(self, global_model_config: ModelConfig):
        """ Replaces all model_config data for agent with a real model config object. """
        self.global_model_config = global_model_config

        for field_name, field_value in self.__dict__.items():
            if isinstance(field_value, AgentConfig):
                field_value.model_config_ = self._resolve_model_config(field_value, global_model_config)

            elif isinstance(field_value, ActionManagerConfig):
                field_value.code_agent.model_config_ = self._resolve_model_config(field_value.code_agent, global_model_config)
                field_value.think_agent.model_config_ = self._resolve_model_config(field_value.think_agent, global_model_config)

class MainConfig:
    """
    MainConfig is a class which is used to handle the config file.
    Contains all other configs.
    """
    def __init__(self, config_file: str):
        load_dotenv()

        self._config_file: str = config_file

        self._config: Config
        self._config_text: str

        self._API_KEY = os.getenv("API_KEY")

        try:
            with open(self._config_file, "r") as f:
                self._config_text = "".join(f.readlines())

        except FileNotFoundError as e:
            logger.error(f"FileNotFound for {self._config_file}")
            exit(1)

        self._config = json.loads(self._config_text)

        self.global_model_config = ModelConfig(api_key = self._API_KEY, **self._config["model"])
        self.prometheus_config = PrometheusConfig(**self._config["prometheus"])

        self.prometheus_config.init_model_cfg(self.global_model_config)

        logger.debug("Successfully initialized main config.")

    def get_agent_by_name(self, agent_name: str):
        """
        Returns AgentConfig object by searching for agent_name
        :param agent_name:
        :return:
        """
        agent: AgentConfig | None = None

        if hasattr(self.prometheus_config, agent_name):
            agent = getattr(self.prometheus_config, agent_name)

        if hasattr(self.prometheus_config.action_manager, agent_name):
            agent =  getattr(self.prometheus_config.action_manager, agent_name)

        if isinstance(agent, AgentConfig):
            return agent

        return None

    def get_api_response(self):
        """Returns an API safe response for the config."""
        return self.prometheus_config.get_public()